test("legacy hidden saved state starts visible and is discarded at addon startup", function()
    assertEquals("healing", SpellMeterDB.mode)
    assertEquals("TOP", SpellMeterDB.point)
    assertEquals(12, SpellMeterDB.x)
    assertEquals(-9, SpellMeterDB.y)
    assertNil(SpellMeterDB.shown)
    assertNotNil(SpellMeterFrame)
    assertTrue(SpellMeterFrame:IsShown())
end)
